config/routes.rb
Parklife.application.config.on_404 = :warn

Rails.application.routes.draw do
  get "*path", to: "redirects#show", constraints: ->(req) { Redirect.all.key? req.path.sub(%r{\A/}, "").sub(%r{/\z}, "") }

  root "posts#index"
  get "/posts/:page", to: "posts#index", constraints: { page: /\d+/ }, as: :posts
  get "/:year/:month/:slug", to: "posts#show", as: :slugged_post, constraints: { year: /\d*/, month: /\d*/, slug: /.*/, format: /html/ }
  direct :post do |post, options|
    route_for :slugged_post, post.published_at.year, post.published_at.month, post.slug, **options
  end

  get "about", to: "pages#about"
  get "archives", to: "pages#archives"
  get "books", to: "pages#books"
  get "tags", to: "pages#tags"
  get "posts/tags/:tag_slug", to: "posts#tag", as: :tag
  get "search", to: "pages#search", format: :html
  get "search", to: "pages#search", format: :json

  get "feed", to: "pages#feed", as: :feed, format: :xml

  get "redirects", to: "redirects#index"

  resources :bookmarks, only: [:index]
  get "/bookmarks/:year/:month/:slug", to: "bookmarks#show", as: :slugged_bookmark, constraints: { year: /\d*/, month: /\d*/, slug: /.*/, format: /html/ }

  direct :bookmark do |bookmark, options|
    route_for :slugged_bookmark, year: bookmark.date.year, month: bookmark.date.month, slug: bookmark.slug, **options
  end

  get 'robots', to: 'robots#robots', as: :robots, format: :txt, defaults: { format: :txt }
  get 'sitemap', to: 'robots#sitemap', as: :sitemap, format: :xml, defaults: { format: :xml }
end

app/models/bookmark.rb
class Bookmark < ApplicationModel
  attr_reader :filepath, :frontmatter, :body

  def self.all
    @bookmarks ||= Dir.glob("#{Rails.root}/_bookmarks/**/*.*").map do |filepath|
      Bookmark.from_file(filepath)
    end
  end

  def self.reset
    @bookmarks = nil
  end

  def self.from_file(path)
    parsed = FrontMatterParser::Parser.parse_file(path)
    new(filepath: path, frontmatter: parsed.front_matter, body: parsed.content)
  end

  def initialize(filepath:, frontmatter:, body:)
    @filepath = filepath
    @frontmatter = frontmatter
    @body = body
  end

  def slug
    @slug ||= begin
      _year, _month, _day, slug = filename.split("-", 4)
      slug
    end
  end

  def filename
    File.basename(filepath, '.*')
  end

  def project_filepath
    filepath.sub("#{Rails.root}/", "")
  end

  def title
    frontmatter.fetch("title", link)
  end

  def link
    frontmatter.fetch("link", "")
  end

  def date
    if frontmatter["date"]
      Time.parse(frontmatter["date"])
    else
      File.mtime(filepath)
    end
  end

  def content
    Kramdown::Document.new(body, input: 'GFM').to_html.html_safe
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all.sort_by(&:date).reverse
  end

  def show
    slug_param = params[:slug].sub(/\.[^.]*\z/, "").downcase
    @bookmark = Bookmark.all.find { |post| post.slug.downcase == slug_param }
    raise ActionController::RoutingError, "Not Found" unless @bookmark
  end
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController
  layout false, only: :show

  def index
    @redirects = Redirect.all
  end

  def show
    target = Redirect.all[params[:path]]

    @redirect = case target
    when String then "/" + target
    when Post then post_path(target)
    else
      raise ActionController::RoutingError, "No redirect found for #{params[:path]}"
    end
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  layout false

  def robots
  end

  def sitemap
    @entries = []

    @entries << SitemapEntry.new(loc: root_url)
    @entries << SitemapEntry.new(loc: about_url)

    @entries += Post.all.map do |post|
      SitemapEntry.new(loc: post_url(post))
    end
  end

  class SitemapEntry
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :loc, :string
    attribute :lastmod, :datetime, default: -> { Time.current }
    attribute :changefreq, :string, default: "daily"
    attribute :priority, :float, default: 1.0
  end
end

app/views/bookmarks/index.html.erb
<% content_for :title, "Bookmarks" %>

<h1>Bookmarks</h1>

<table class="table">
  <thead>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th style="max-width: 20em">Description</th>
    <th>Permalink</th>
  </tr>
  </thead>
  <tbody>
  <% @bookmarks.each do |bookmark| %>
    <tr>
      <td>
        <time><%= bookmark.date.strftime("%Y-%m-%d") %></time>
      </td>
      <td>
        <a class="post-link" href="<%= bookmark.link %>">
          <%= bookmark.title&.truncate(50) %>
        </a>
      </td>
      <td style="max-width: 20em"><%= bookmark.content %></td>
      <td>
        <%= link_to "Permalink", bookmark_path(bookmark) %>
        /
        <a href="<%= "https://github.com/bensheldon/island94.org/blob/main/#{bookmark.project_filepath}" %>">
          <i class="bi bi-github"></i>Edit
        </a>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/bookmarks/show.html.erb
<article class="post" itemscope itemtype="http://schema.org/BlogPosting">
  <header class="post-header">
    <h1 class="post-title" itemprop="name headline">
      <%= link_to (@bookmark.title.presence || @bookmark.link), bookmark_path(@bookmark), class: "post-link" %>
    </h1>
    <small><%= link_to @bookmark.link, @bookmark.link %></small>
    <p>
      <% if @bookmark.date %>
        <time datetime="<%= @bookmark.date.to_time.xmlschema %>" itemprop="datePublished">
          <%= @bookmark.date.strftime("%B %-d, %Y") %>
        </time>
      <% end %>
    </p>
  </header>

  <div class="post-content" itemprop="articleBody">
    <%= @bookmark.content %>
  </div>
</article>

app/views/layouts/_base.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= "#{content_for(:title)} | Island94.org" || "Island94.org" %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="alternate" type="application/rss+xml" title="Island94.org" href="<%= feed_url(format: :xml) %>">

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "main" %>

  <script>
    let theme = localStorage.getItem('theme');
    if (!["light", "dark"].includes(theme)) {
      theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    document.documentElement.setAttribute('data-bs-theme', theme);
  </script>

  <%= yield :head %>
</head>
<body>
<%= render "layouts/navbar" %>
<%= yield %>
</body>
</html>

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light mb-2 flex-column">
  <div class="container">
    <a class="navbar-brand" href="/">Island94.org</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to "About", about_path, class: ["nav-link", active: current_page?(about_path)] %></li>
        <li class="nav-item"><%= link_to "Archives", archives_path, class: ["nav-link", active: current_page?(archives_path)] %></li>
        <li class="nav-item"><%= link_to "Tags", tags_path, class: ["nav-link", active: current_page?(tags_path)] %></li>
        <li class="nav-item"><%= link_to feed_path(format: :xml), class: "nav-link" do %>RSS Feed <i class="bi bi-rss-fill"></i><% end %></li>

        <li class="nav-item py-2 py-lg-1 col-12 col-lg-auto">
          <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-light-500"></div>
          <hr class="d-lg-none my-0 text-light-500">
        </li>

        <li class="nav-item dropdown">
          <button id="bs-theme" class="btn btn-link nav-link dropdown-toggle" type="button" aria-expanded="false" data-bs-toggle="dropdown"  aria-label="Theme (Auto)">
            <i data-bs-theme-active-icon class="bi bi-circle-half"></i>
            <span data-bs-theme-label>Theme</span>
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bs-theme-text">
            <li>
              <button type="button" class="dropdown-item" data-bs-theme-value="light" aria-pressed="false">
                <i class="bi bi-sun"></i> Light
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item" data-bs-theme-value="dark" aria-pressed="false">
                <i class="bi bi-moon-stars-fill"></i> Dark
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item" data-bs-theme-value="auto" aria-pressed="true">
                <i class="bi bi-circle-half"></i> Auto
              </button>
            </li>
          </ul>
        </li>

      </ul>

      <form id="search" class="d-flex" action="/search" method="get">
        <input id="search-box" class="form-control search" role="search" name="q" placeholder="Search" aria-label="Search" results="0" type="text">
        <button class="visually-hidden" type="submit">Search</button>
      </form>
    </div>
  </div>
  <div class="container">
    <div class="text-muted fst-italic">
      — Ben Sheldon's personal blog and <a href="/2012/04/A-Commonplace-Book.html">commonplace book</a>.
    </div>
  </div>
</nav>

app/views/layouts/narrow.html.erb
<%= render layout: "layouts/base" do %>
  <div class="container container-body">
    <%= yield %>
  </div>
<% end %>

app/views/pages/archives.html.erb
<h1>Archives</h1>

<% posts_by_year = @posts.group_by { |post| post.published_at.strftime('%Y') } %>
<% posts_by_year.each do |year, year_posts| %>
  <h2><%= year %></h2>

  <% posts_by_month = year_posts.group_by { |post| post.published_at.strftime('%B') } %>
  <% posts_by_month.each do |month, month_posts| %>
    <h3 class="h6"><%= month %></h3>
    <ul>
      <% month_posts.sort_by(&:published_at).reverse.each do |post| %>
        <li><%= link_to post.title, post_path(post) %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/pages/feed.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Island94.org</title>
    <description>A Lost and Found</description>
    <link><%= root_url %></link>
    <atom:link href="<%= feed_url(format: :xml) %>" rel="self" type="application/rss+xml"/>
    <pubDate><%= @posts.first.published_at.rfc822 %></pubDate>
    <lastBuildDate><%= Time.now.rfc822 %></lastBuildDate>
    <generator>Ruby on Rails</generator>
    <% @posts.each do |post| %>
      <item>
        <title><%= h post.title %></title>
        <description>
          <![CDATA[
          <%= h post.content %>
          ]]>
        </description>
        <link><%= post_url(post) %></link>
        <guid isPermaLink="true"><%= post_url(post) %></guid>
        <pubDate><%= post.published_at.rfc822 %></pubDate>
      </item>
    <% end %>
  </channel>
</rss>

app/views/pages/search.html.erb
<h1>Search results</h1>
<div id="search-results">
  <em>Loading...</em>
</div>

<%= javascript_include_tag "search" %> 

app/views/pages/search.json.erb
<%
  posts_hash = Post.all.sort_by(&:published_at).reverse.each_with_object({}) do |post, hash|
    hash[post_path(post).delete_prefix('/').parameterize] = {
      title: post.title,
      published: post.published_at.strftime("%B %-d, %Y"),
      tags: post.tags,
      content: strip_tags(post.content),
      url: post_path(post)
    }
  end
%>
<%== posts_hash.to_json %>

app/views/pages/tags.html.erb
<%# First, collect and sort all unique tags %>
<% all_tags = Post.all.flat_map(&:tags) %>
<% tag_counts = all_tags.tally %>
<% sorted_tags = tag_counts.keys.sort_by(&:downcase) %>

<ul class="list-unstyled list-columns">
  <% sorted_tags.each do |tag| %>
    <% tag_slug = tag.downcase.gsub(' ', '_') %>
    <li>
      <%= link_to tag, tag_path(tag_slug) %>
      (<%= tag_counts[tag] %>)
    </li>
  <% end %>
</ul>

app/views/posts/_post.erb
<article class="post" itemscope itemtype="http://schema.org/BlogPosting">
  <header class="post-header">
    <h1 class="post-title" itemprop="name headline">
      <a class="post-link" href="<%= post_path(post) %>"><%= markdownify(post.title) %></a>
    </h1>
    <p class="post-meta text-muted">
      <% if post.published_at %>
        <time datetime="<%= post.published_at.iso8601 %>" itemprop="datePublished"><%= post.published_at.strftime("%B %-d, %Y") %></time>
      <% end %>

      <% if post.tags.any? %>
        • Tagged <%= to_sentence post.tags %>
      <% end %>
    </p>
  </header>

  <div class="post-content" itemprop="articleBody">
    <%= post.content %>
  </div>
</article>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>

<div class="container container-body">
  <%= render "post", post: @post %>

  <div class="card my-4">
    <div class="card-body">
      Discuss this with me on <a href="https://twitter.com/bensheldon"><i class="bi bi-twitter"></i> Twitter</a>
      or suggest a
      <a href="https://github.com/bensheldon/island94.org/blob/main/<%= @post.project_filepath %>"><i class="bi bi-github"></i>
        change</a>.
    </div>
    <% if @post.related_posts.any? %>
      <hr>
      <div class="card-body">
        <h5>Related Posts</h5>
        <ul>
          <% @post.related_posts.each do |related_post| %>
            <li><%= link_to related_post.title, post_path(related_post) %></li>
          <% end %>
        </ul>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/tag.html.erb
<h1>Posts tagged with "<%= @tag %>"</h1>

<% posts_by_year = @posts.group_by { |post| post.published_at.strftime('%Y') } %>
<% posts_by_year.each do |year, year_posts| %>
  <h2><%= year %></h2>

  <% posts_by_month = year_posts.group_by { |post| post.published_at.strftime('%B') } %>
  <% posts_by_month.each do |month, month_posts| %>
    <h3 class="h6"><%= month %></h3>
    <ul>
      <% month_posts.sort_by(&:published_at).reverse.each do |post| %>
        <li><%= link_to post.title, post_path(post) %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<p>
  <%= link_to "← Back to all tags", tags_path %>
</p> 

app/views/redirects/index.html.erb
<h1>Redirects</h1>

<ul>
  <% @redirects.each do |from, to| %>
    <li>
      <%= link_to from, "/" + from %>
    </li>
  <% end %>
</ul>

app/views/redirects/show.html.erb
<!DOCTYPE html>
<html lang="en-US">
<meta charset="utf-8">
<title>Redirecting&hellip;</title>
<link rel="canonical" href="<%= @redirect %>">
<script>location="<%= @redirect %></script>
<meta http-equiv="refresh" content="0; url=<%= @redirect %>">
<meta name="robots" content="noindex">
<h1>Redirecting&hellip;</h1>
<a href="<%= @redirect %>">Click here if you are not redirected.</a>
</html>

app/views/robots/robots.text.erb
Sitemap: <%= sitemap_url(format: :xml) %>

app/views/robots/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <% @entries.each do |entry| %>
     <url>
      <loc><%= entry.loc %></loc>
      <lastmod><%= entry.lastmod.utc.strftime("%Y-%m-%d") %></lastmod>
      <changefreq><%= entry.changefreq %></changefreq>
      <priority><%= entry.priority %></priority>
    </url>
  <% end %>
</urlset>